# THIS IS A FILE TO STORE AND EDIT VARIOUS VARIABLES TO FINE TUNE THE EXPERIENCE YOU WANT.


# FILE NAME: WHAT YOU WANT TO CALL YOUR DATABASE; CHANGE IF YOU WANT TO JUGGLE MULTIPLE FILES RATHER THAN OVERWRITE
file_name: str = "tolkien_elves_600_revised"

# AGE OF ADULTHOOD: BARE MINIMUM AGE TO HAVE CHILDREN - DEFAULT 50
adulthood: int = 50

# LENGTH OF PREGNANCY - DEFAULT 10 YEARS
pregnancy: int = 10

# TIME BETWEEN PREGNANCIES - DEFAULT 10 YEARS
time_between_children: int = 10

# STARTING POPULATION - DEFAULT IS 144
starting_population: int = 144

# INFANT IMMORTALITY: BARE MINIMUM AGE BEFORE CHILDREN ARE AT RISK OF DEATH - DEFAULT 5 YEARS
infant_immortality: int = 5

# START YEAR - DEFAULT 1
start_year: int = 1

# END YEAR - DEFAULT 600
end_year: int = 600

# CHILD CONCEPTION CHANCE: LIKELIHOOD OF A COUPLE WHO *CAN* CONCIEVE A GIVEN YEAR CHOOSING TO DO SO; ACTS AS A PERCENTAGE OUT OF 100 - DEFAULT 40
child_chance: int = 40

# DEATH DIVISOR: 